title: "Tower of Hanoi docs"
remote_theme: pmarsceill/just-the-docs
color_scheme: hanoi


search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/gameFront.png"


aux_links:
  "towerofhanoi.app":
    - "//towerofhanoi.app"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 Justin Philpott. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-1G034MGDSY
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)
